// Metamask & Drizzle
export const CHECK_METAMASK = 'CHECK_METAMASK';
export const CHECK_METAMASK_DONE = 'CHECK_METAMASK_DONE';
export const TX_ERROR_METAMASK = 'TX_ERROR_METAMASK';
export const TX_ERROR_METAMASK_DONE = 'TX_ERROR_METAMASK_DONE';
export const TX_SUCCESSFUL_UPDATE_UI = 'TX_SUCCESSFUL_UPDATE_UI';
export const CHECKING_TX_UI = 'CHECKING_TX_UI';
export const CHECKING_TX_UI_DONE = 'CHECKING_TX_UI_DONE';
export const SET_DRIZZLE_STATE = 'SET_DRIZZLE_STATE';
export const GETTING_STORED_VALUE = 'GETTING_STORED_VALUE';
export const GOT_STORED_VALUE = 'GOT_STORED_VALUE';
export const GET_STORED_VALUE = 'GET_STORED_VALUE';
export const PUSH_TO_TXSTACK = 'PUSH_TO_TXSTACK';
export const TX_ERROR = 'TX_ERROR';
export const TX_BROADCASTED = 'TX_BROADCASTED';
export const TX_SUCCESSFUL = 'TX_SUCCESSFUL';
